// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassportApi.Data;

namespace PassportApi.Migrations
{
    [DbContext(typeof(PassportDbContext))]
    [Migration("20210319043010_passporttable")]
    partial class passporttable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PassportApi.Models.Passport", b =>
                {
                    b.Property<int>("PPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PPExpiry")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("PPHolderName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PPNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PPOcode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.HasKey("PPId");

                    b.ToTable("Passport");
                });
#pragma warning restore 612, 618
        }
    }
}
